### ISSUE TITLE
AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by mosheliv** [ZFTurbo/Keras-inference-time-optimizer#12]
Hi,
I have just got around for trying to improve inference. unfortunatly, it still fails:

```
    model = reduce_keras_model(model)
  File "/home/m/.local/lib/python2.7/site-packages/kito/__init__.py", line 334, in reduce_keras_model
    new_layer = reduce_keras_model(new_layer, verbose=verbose)
  File "/home/m/.local/lib/python2.7/site-packages/kito/__init__.py", line 351, in reduce_keras_model
    output_tensor, output_names = get_layers_without_output(tmp_model, verbose)
  File "/home/m/.local/lib/python2.7/site-packages/kito/__init__.py", line 145, in get_layers_without_output
    output_tensor = model.outputs.copy()
AttributeError: 'list' object has no attribute 'copy'

```

**Comment by ZFTurbo** [comment]
Do you have example of model which fails?

**Comment by mosheliv** [comment]
Same as before. Nothing have changed as far as i know.

**Comment by ZFTurbo** [comment]
It's the problem with Python 2:
https://stackoverflow.com/questions/2612802/how-to-clone-or-copy-a-list

I will change this part of code to work in Python 2 as well and write here when it's done.

**Comment by ZFTurbo** [comment]
Updated to 1.0.2. Must work now)

**Comment by mosheliv** [comment]
all my gpus are training... will do inference tomorrow and let you know.
Thank you!!!!

**Comment by mosheliv** [comment]
It worked on inceptionresnetv2 but there was no performance gain. Ill try again with resnet later.
Thank you for the support!
