### ISSUE TITLE
Reduced Model Export

### ISSUE THREAD

**Issue by JPery** [ZFTurbo/Keras-inference-time-optimizer#20]
Is there any way to export the model so we can avoid converting the model each time?

**Comment by ZFTurbo** [comment]
Sure. You can just save it as any other Keras model:

```python
from kito import reduce_keras_model
model_reduced = reduce_keras_model(model)
model_reduced.save(output_path)
```

**Comment by JPery** [comment]
Thank you for your fast answer. 

This is a nice project. It reduced mi inference time from 120 to 50 seconds. Great job!
