### ISSUE TITLE
Model is not correct when has multiple inputs and outputs

### ISSUE THREAD

**Issue by mrlzla** [ZFTurbo/Keras-inference-time-optimizer#3]
At the last line of reduce_keras_model method one creates model that have only one input and one output, it's not true in general since keras model can get multiple inputs and multiple outputs.

**Comment by ZFTurbo** [comment]
Thank you. I guess we need to create some generic test for such case.

I also know the problem with complex models which included other models as layers. Code won't work on them as well. For example: RetinaNet.

**Comment by ZFTurbo** [comment]
The problem was fixed. Test with multi input and multi output was added.

**Comment by mrlzla** [comment]
Good job!
